# Replace "15. Application properties packaged inside your jar (application.properties and YAML variants)" with "4. Command line arguments"
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config
line.bot:
  channel-token: token
  channel-secret: secret
  handler.path: /path
